// <auto-generated />
using FakturacniSystem.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakturacniSystem.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20251007060747_school")]
    partial class school
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FakturacniSystem.Code.Polozka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pocet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Polozky");
                });
#pragma warning restore 612, 618
        }
    }
}
